### ISSUE TITLE
Show badge with number of accounts (real) that topic has

### ISSUE THREAD

**Issue by cody-code-wy** [tweet-squared/Tweets-Squared-App#69]
On the topics page show badges with the number of real account that the topic has. so it should look like

- Politics (9)
- Celebs (9001)

**Comment by monicamow** [comment]
THIS IS A CHERRY ****

**Comment by tjukes** [comment]
New branch show_badges_topic_accounts has this -- not fancy or pretty yet though.

**Comment by cody-code-wy** [comment]
Pending PR with css. PR #91

**Comment by cody-code-wy** [comment]
In development.
